### ISSUE TITLE
Crash on iPad - device does not support AVCaptureSessionPreset1280x720

### ISSUE THREAD

**Issue by katzlbt** [zxingify/zxingify-objc#475]
Scanning crashes on iPad (with iOS 9.3.5 probably newer versions too) because the requested AVCaptureSessionPreset1280x720 is not available.  

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Can't add <AVCaptureDeviceInput: 0x17de0180 [Frontkamera]> because the device does not support AVCaptureSessionPreset1280x720.  Use -[AVCaptureDevice supportsAVCaptureSessionPreset:].'

https://github.com/zxingify/zxingify-objc/blob/270ef2d958e7590394bb2af2a93923f4014ffc88/ZXingObjC/client/ZXCapture.m#L575

**Comment by katzlbt** [comment]
This change seems to fix the problem:

      self.sessionPreset = AVCaptureSessionPresetMedium;

**Comment by Malachi-Holden** [comment]
I am having this issue with an iPad 2 and an iPhone 6. Changing self.sessionPreset made the error message go away, but it still crashes. Right now the only fix I could come up with is to revert to version 3.1.0.

**Comment by benjohnde** [comment]
Unfortunately, I can no longer provide support for this codebase, the topic will be closed. I recommend to take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!

Hopefully this is fixed in the current master with the overhaul of the sample app, cf. #527.
