### ISSUE TITLE
Extremely low speed and accuracy for GS1 DataBar Expanded Stacked (also known as RSS14). Help needed 🙏

### ISSUE THREAD

**Issue by IVANKRUPSKI** [zxingify/zxingify-objc#501]
Hello everyone!

I am facing an issue with complex barcode formats, such as GS1 DataBar Expanded Stacked (also know as RSS14).
It's very badly scanned. However, I know it's possible to increase accuracy and speed. It can be easily scanned with zxingify-objc.

I have tried all the possible hints (hints.tryHarder, etc.), separate reader formats, kind of ZXRSS14Reader() and others, nothing helps.

I wanted to try _capture.enableHeuristic(), but there is a crash (https://github.com/zxingify/zxingify-objc/issues/500)

Is there any way to significantly improve speed/accuracy?

Any ideas will be highly appreciated.

**Comment by IVANKRUPSKI** [comment]
Hello,

Some more details on this issue.

As already mentioned, we have a problem with scanning “GS1 DataBar Expanded”.

However, I am not sure that the problem is purely in the “GS1 DataBar Expanded” format. I assume, based on our tests, that the problem is in general image preparation (resolution, black/white pixels separation, etc.) before actually real recognition starts. GS1 DataBar Expanded is just really a complex format compared to other formats and apparently therefore it has more problems than other formats. But this is just my assumption.

Here are two images of the same GS1 DataBar Expanded.
![image](https://user-images.githubusercontent.com/16180201/96149433-9db5ed00-0f09-11eb-9d66-692d46b7f928.png)

1 - generated on the computer on the screen, so white is white, black is black. [ScannableOK.png.zip](https://github.com/zxingify/zxingify-objc/files/5385863/ScannableOK.png.zip)

2 - photo from a retailer plastic card, so white is not really white and black is not really black, and resolution apparently is a bit worse. 
[ScannableWithProblems.png.zip](https://github.com/zxingify/zxingify-objc/files/5385865/ScannableWithProblems.png.zip)

The reason why I am writing about the white and black colours is because I assume there it is somehow related to the issue. 1st image is much easier scanned while the second image is not. And moreover, when I try to scan the code from the real plastic card (from which I actually made a photo for image 2) it’s even worse than when I scan from its photo.

I have also noticed that scanning of image 2 is better on iPhone 11 and worse on iPhone 6sPlus. Among other, based on that I made an assumption that the problem is somehow linked to the image resolution (preparation) before actual recognition.

And, obviously, these isseus don’t appear on Android.

##Additional
There also a problem in this function in your example, however it’s not related to the problem of “GS1 DataBar Expanded”
![image](https://user-images.githubusercontent.com/16180201/96149660-dce43e00-0f09-11eb-852a-5a862d81d57e.png)

- This function -func applyRectOfInterest(orientation: UIInterfaceOrientation)- somehow works wrong on iPhone 11. The scanning is really bad on iPhone, but when I comment this function, the scanning becomes much better. While on iPhone 6s+ this problem doesn’t appear. So something wrong with applyRectOfInterest function

**Comment by eteamIH** [comment]
I'm facing a similar issue on iPhone 11 Pro. 

I've tested different RSS EXPANDED barcodes on iPhone 6 (iOS 12), iPhone 6s (iOS 14.4), iPhone SE 2020 (iOS 14.3) and iPhone 11 Pro (iOS 14.4).

I've noticed that scanning performance and accuracy is best on iPhone SE 2020 while it seems to be not working at all on iPhone 11 Pro.

If anyone has found a fix for iPhone 11 Pro then kindly share it here as I'm stuck since I'm developing an app where the core functionality is related to RSS EXPANDED scanning.

Thanks

**Comment by sandy105** [comment]
@eteamIH  same as me， do you have any solution？

**Comment by eteamIH** [comment]
@sandy105 We have a react-native project and were exploring this library as a native module but wasn't feasible since it doesn't work well on newer iPhones.

We then tried another react-native package, [react-native-barcode](https://github.com/yvvw/react-native-barcode) but it wasn't scanning from the camera. However, it does scan GS1 Databar very efficiently from images. So this can be a viable solution if you need scanning from an image.

But now we are looking at paid options like Cognex since open source options don't seem to be working well on newer devices.

**Comment by benjohnde** [comment]
This is a barely maintained ZXing port, I'd rather take a look at https://github.com/zxing-cpp/zxing-cpp created and maintained by the very ambitious @axxel!
